[package]
name = "saber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_core = "0.6.4"
sha3 = { version = "0.10.8", default-features = false }
subtle = "2.5.0"

[dev-dependencies]
rand = "0.8.5"
criterion = "0.3"

[[bench]]
name = "all"
harness = false
